services:
    security.authentication.listener.mmc:
        class: Mmc\Security\Firewall\MmcJsonListener
        abstract: true
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@security.http_utils'
            - ''
            - ''
            - ''
            - []
            - '@logger'
            - '@event_dispatcher'
        tags:
            - { name: monolog.logger, channel: security }

    security.authentication.provider.mmc:
        class: Mmc\Security\Authentication\Provider\MmcProvider
        arguments:
            - '' #UserProvider
            - [] #Authenticators

    security.authentication.provider.mmc.authenticators.token_by_email:
        class: Mmc\Security\Authentication\Authenticator\TokenByEmailAuthenticator
        arguments:
            - '@security.encoder_factory'

    security.authentication.provider.mmc.authenticators.username_password:
        class: Mmc\Security\Authentication\Authenticator\UsernamePasswordAuthenticator
        arguments:
            - '@security.encoder_factory'

    security.user.provider.mmc:
        class: Mmc\Security\User\Provider
        arguments:
            - '@doctrine.orm.entity_manager'

    security.mmc.interactive_login_listener:
        public: false
        class: Mmc\Security\Event\AuthenticationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    security.mmc.listener.authentication_activity:
        public: false
        class: Mmc\Security\Event\AuthenticationActivityListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.success, method: onAuthenticationSuccess }
            - { name: kernel.event_listener, event: security.mmc.logout.success, method: onLogoutSuccess }

    security.mmc.listener.authentication_session:
        public: false
        class: Mmc\Security\Event\AuthenticationSessionListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.success, method: onAuthenticationSuccess }
            - { name: kernel.event_listener, event: security.mmc.logout.success, method: onLogoutSuccess }

    security.mmc.listener.authentication_token_by_email:
        public: false
        class: Mmc\Security\Event\AuthenticationTokenByEmailListener
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.success, method: onAuthenticationSuccess }

    security.mmc.logout.handler:
        public: false
        class: Mmc\Security\Logout\LogoutHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    security.mmc.logout.handler_success:
        public: false
        class: Mmc\Security\Logout\LogoutSuccessHandler

    security.mmc.service.authentication_token_by_email_refresher:
        alias: Mmc\Security\Service\AuthenticationTokenByEmailRefresher
        public: true

    Mmc\Security\Service\AuthenticationTokenByEmailRefresher:
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@security.mmc.service.number_base_token_generator'
            - '1 minute'
            - '5 minutes'

    security.mmc.service.number_base_token_generator:
        class: Mmc\Security\Service\NumberBaseTokenGenerator
        arguments:
            - 6
