services:
    security.authentication.listener.mmc:
        class: Mmc\Security\Firewall\MmcJsonListener
        abstract: true
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@security.http_utils'
            - ''
            - ''
            - ''
            - []
            - '@logger'
            - '@event_dispatcher'
        tags:
            - { name: monolog.logger, channel: security }

    security.authentication.provider.mmc:
        class: Mmc\Security\Authentication\Provider\MmcProvider
        arguments:
            - '' #UserProvider
            - [] #Authenticators

    security.authentication.provider.mmc.authenticators.token_by_email:
        class: Mmc\Security\Authentication\Authenticator\TokenByEmailAuthenticator
        arguments:
            - '@security.encoder_factory'

    security.authentication.provider.mmc.authenticators.username_password:
        class: Mmc\Security\Authentication\Authenticator\UsernamePasswordAuthenticator
        arguments:
            - '@security.encoder_factory'

    security.authentication.provider.mmc.authenticators.anonymous:
        class: Mmc\Security\Authentication\Authenticator\AnonymousAuthenticator

    security.mmc.command.create_anonymous_user:
        class: Mmc\Security\Command\CreateAnonymousUserCommand
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: console.command }

    security.user.provider.mmc:
        class: Mmc\Security\User\Provider
        arguments:
            - '@doctrine.orm.entity_manager'

    security.mmc.interactive_login_listener:
        public: false
        class: Mmc\Security\Event\AuthenticationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    security.mmc.listener.authentication_activity:
        public: false
        class: Mmc\Security\Event\AuthenticationActivityListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.interactive_success, method: onAuthenticationInteractiveSuccess }
            - { name: kernel.event_listener, event: security.mmc.logout.success, method: onLogoutSuccess }
            - { name: kernel.event_listener, event: security.mmc.authentication.change_password, method: onPasswordChange }
            - { name: kernel.event_listener, event: security.mmc.authentication.change_username, method: onUsernameChange }
            - { name: kernel.event_listener, event: security.mmc.authentication.refresh_token_by_email, method: onRefreshTokenByEmail }
            - { name: kernel.event_listener, event: security.mmc.authentication.token_by_email_has_been_verified, method: onVerifyTokenByEmail }
            - { name: kernel.event_listener, event: security.mmc.authentication.change_email, method: onEmailChange }

    security.mmc.listener.authentication_session:
        public: false
        class: Mmc\Security\Event\AuthenticationSessionListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.mmc.service.session_ttl_provider'
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.interactive_success, method: onAuthenticationInteractiveSuccess }
            - { name: kernel.event_listener, event: security.mmc.authentication.success, method: onAuthenticationSuccess }
            - { name: kernel.event_listener, event: security.mmc.logout.success, method: onLogoutSuccess }

    security.mmc.listener.authentication_token_by_email:
        public: false
        class: Mmc\Security\Event\AuthenticationTokenByEmailListener
        tags:
            - { name: kernel.event_listener, event: security.mmc.authentication.interactive_success, method: onAuthenticationInteractiveSuccess }

    security.mmc.logout.handler:
        public: false
        class: Mmc\Security\Logout\LogoutHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    security.mmc.logout.handler_success:
        public: false
        class: Mmc\Security\Logout\LogoutSuccessHandler

    security.mmc.service.authentication_token_by_email_refresher:
        alias: Mmc\Security\Service\AuthenticationTokenByEmailRefresher
        public: true

    Mmc\Security\Service\AuthenticationTokenByEmailRefresher:
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@security.mmc.service.number_base_token_generator'
            - '1 minute'
            - '5 minutes'
            - '@event_dispatcher'
            - '@security.token_storage'

    security.mmc.service.authentication_token_by_email_verifier:
        alias: Mmc\Security\Service\AuthenticationTokenByEmailVerifier
        public: true

    Mmc\Security\Service\AuthenticationTokenByEmailVerifier:
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@event_dispatcher'
            - '@security.token_storage'

    security.mmc.service.authentication_token_by_email_updater:
        alias: Mmc\Security\Service\AuthenticationTokenByEmailUpdater
        public: true

    Mmc\Security\Service\AuthenticationTokenByEmailUpdater:
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@validator'

    security.mmc.service.number_base_token_generator:
        class: Mmc\Security\Service\NumberBaseTokenGenerator
        arguments:
            - 6

    security.mmc.service.session_ttl_provider:
        public: false
        class: Mmc\Security\Service\SessionTTLProvider
        arguments:
            - []

    security.mmc.service.authentication_username_password_updater:
        alias: Mmc\Security\Service\AuthenticationUsernamePasswordUpdater
        public: true

    Mmc\Security\Service\AuthenticationUsernamePasswordUpdater:
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@validator'
